// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: MonitorComms.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitorCommsClient is the client API for MonitorComms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorCommsClient interface {
	Inform(ctx context.Context, in *Info, opts ...grpc.CallOption) (*MonitorResponse, error)
}

type monitorCommsClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorCommsClient(cc grpc.ClientConnInterface) MonitorCommsClient {
	return &monitorCommsClient{cc}
}

func (c *monitorCommsClient) Inform(ctx context.Context, in *Info, opts ...grpc.CallOption) (*MonitorResponse, error) {
	out := new(MonitorResponse)
	err := c.cc.Invoke(ctx, "/main.MonitorComms/Inform", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorCommsServer is the server API for MonitorComms service.
// All implementations must embed UnimplementedMonitorCommsServer
// for forward compatibility
type MonitorCommsServer interface {
	Inform(context.Context, *Info) (*MonitorResponse, error)
	mustEmbedUnimplementedMonitorCommsServer()
}

// UnimplementedMonitorCommsServer must be embedded to have forward compatible implementations.
type UnimplementedMonitorCommsServer struct {
}

func (UnimplementedMonitorCommsServer) Inform(context.Context, *Info) (*MonitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inform not implemented")
}
func (UnimplementedMonitorCommsServer) mustEmbedUnimplementedMonitorCommsServer() {}

// UnsafeMonitorCommsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorCommsServer will
// result in compilation errors.
type UnsafeMonitorCommsServer interface {
	mustEmbedUnimplementedMonitorCommsServer()
}

func RegisterMonitorCommsServer(s grpc.ServiceRegistrar, srv MonitorCommsServer) {
	s.RegisterService(&MonitorComms_ServiceDesc, srv)
}

func _MonitorComms_Inform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorCommsServer).Inform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.MonitorComms/Inform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorCommsServer).Inform(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorComms_ServiceDesc is the grpc.ServiceDesc for MonitorComms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorComms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.MonitorComms",
	HandlerType: (*MonitorCommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inform",
			Handler:    _MonitorComms_Inform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MonitorComms.proto",
}
