// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: ServerComm.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ID for server. Contains address and SHA-1 hash of address
type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Id      []byte  `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServerComm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_ServerComm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_ServerComm_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *ID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ChangeSuccessor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *ID `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	NewSuccessor *ID `protobuf:"bytes,2,req,name=newSuccessor" json:"newSuccessor,omitempty"`
}

func (x *ChangeSuccessor) Reset() {
	*x = ChangeSuccessor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServerComm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSuccessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSuccessor) ProtoMessage() {}

func (x *ChangeSuccessor) ProtoReflect() protoreflect.Message {
	mi := &file_ServerComm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSuccessor.ProtoReflect.Descriptor instead.
func (*ChangeSuccessor) Descriptor() ([]byte, []int) {
	return file_ServerComm_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeSuccessor) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChangeSuccessor) GetNewSuccessor() *ID {
	if x != nil {
		return x.NewSuccessor
	}
	return nil
}

type ChangePredecessor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             *ID `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	NewPredecessor *ID `protobuf:"bytes,2,req,name=newPredecessor" json:"newPredecessor,omitempty"`
}

func (x *ChangePredecessor) Reset() {
	*x = ChangePredecessor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServerComm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePredecessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePredecessor) ProtoMessage() {}

func (x *ChangePredecessor) ProtoReflect() protoreflect.Message {
	mi := &file_ServerComm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePredecessor.ProtoReflect.Descriptor instead.
func (*ChangePredecessor) Descriptor() ([]byte, []int) {
	return file_ServerComm_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePredecessor) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChangePredecessor) GetNewPredecessor() *ID {
	if x != nil {
		return x.NewPredecessor
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServerComm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ServerComm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ServerComm_proto_rawDescGZIP(), []int{3}
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Address        *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	PublicKeyLogin []byte  `protobuf:"bytes,3,req,name=publicKeyLogin" json:"publicKeyLogin,omitempty"`
	PublicKeyChat  []byte  `protobuf:"bytes,4,req,name=publicKeyChat" json:"publicKeyChat,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServerComm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_ServerComm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_ServerComm_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Record) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Record) GetPublicKeyLogin() []byte {
	if x != nil {
		return x.PublicKeyLogin
	}
	return nil
}

func (x *Record) GetPublicKeyChat() []byte {
	if x != nil {
		return x.PublicKeyChat
	}
	return nil
}

var File_ServerComm_proto protoreflect.FileDescriptor

var file_ServerComm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2e, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49,
	0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x49, 0x44, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x22, 0x5f, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x44, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x49, 0x44, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x8c, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x43, 0x68, 0x61, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c,
	0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x43, 0x68, 0x61, 0x74, 0x32,
	0x93, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12,
	0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x44, 0x1a, 0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x44, 0x1a,
	0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x0f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x15, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x08, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x23, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x12, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63,
}

var (
	file_ServerComm_proto_rawDescOnce sync.Once
	file_ServerComm_proto_rawDescData = file_ServerComm_proto_rawDesc
)

func file_ServerComm_proto_rawDescGZIP() []byte {
	file_ServerComm_proto_rawDescOnce.Do(func() {
		file_ServerComm_proto_rawDescData = protoimpl.X.CompressGZIP(file_ServerComm_proto_rawDescData)
	})
	return file_ServerComm_proto_rawDescData
}

var file_ServerComm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ServerComm_proto_goTypes = []interface{}{
	(*ID)(nil),                // 0: main.ID
	(*ChangeSuccessor)(nil),   // 1: main.ChangeSuccessor
	(*ChangePredecessor)(nil), // 2: main.ChangePredecessor
	(*Response)(nil),          // 3: main.Response
	(*Record)(nil),            // 4: main.Record
}
var file_ServerComm_proto_depIdxs = []int32{
	0,  // 0: main.ChangeSuccessor.id:type_name -> main.ID
	0,  // 1: main.ChangeSuccessor.newSuccessor:type_name -> main.ID
	0,  // 2: main.ChangePredecessor.id:type_name -> main.ID
	0,  // 3: main.ChangePredecessor.newPredecessor:type_name -> main.ID
	0,  // 4: main.ServerComms.getSuccessor:input_type -> main.ID
	0,  // 5: main.ServerComms.getPredecessor:input_type -> main.ID
	1,  // 6: main.ServerComms.changeSuccessor:input_type -> main.ChangeSuccessor
	2,  // 7: main.ServerComms.changePredecessor:input_type -> main.ChangePredecessor
	0,  // 8: main.ServerComms.get:input_type -> main.ID
	4,  // 9: main.ServerComms.put:input_type -> main.Record
	0,  // 10: main.ServerComms.getSuccessor:output_type -> main.ID
	0,  // 11: main.ServerComms.getPredecessor:output_type -> main.ID
	3,  // 12: main.ServerComms.changeSuccessor:output_type -> main.Response
	3,  // 13: main.ServerComms.changePredecessor:output_type -> main.Response
	4,  // 14: main.ServerComms.get:output_type -> main.Record
	3,  // 15: main.ServerComms.put:output_type -> main.Response
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ServerComm_proto_init() }
func file_ServerComm_proto_init() {
	if File_ServerComm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ServerComm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServerComm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSuccessor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServerComm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePredecessor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServerComm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServerComm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ServerComm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ServerComm_proto_goTypes,
		DependencyIndexes: file_ServerComm_proto_depIdxs,
		MessageInfos:      file_ServerComm_proto_msgTypes,
	}.Build()
	File_ServerComm_proto = out.File
	file_ServerComm_proto_rawDesc = nil
	file_ServerComm_proto_goTypes = nil
	file_ServerComm_proto_depIdxs = nil
}
